[FIX] website_slides: fix luxon error
HOW TO REPRODUCE
================

- Don't need to login
- From Odoo front-end, go to Courses > Trees, Wood and Gardens >
    Main Trees Categories
- You get the following client error:
    Uncaught Promise > datetimeObj.getTime is not a function

HOW TO SOLVE:
============

Unlike standard JS equivalent, luxon datetime objects don't have a
getTime() function. Replace it by valueOf() function.

see bb09cf76e32b20864dc45eacf912d2c6f26768ef

task-3632077

closes odoo/odoo#145573

Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>